version: '3'
services:
  haproxy:
    image: wind634/haproxy-redis:ha
    labels:
      - "io.daocloud.dce.service.role=proxy"
      - "io.daocloud.dce.service.console=true"
      - io.daocloud.dce.compose.placement.constraints=["node.labels.redis == redis"]
    ports:
      - "6379:6379"
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg
#    cpu_quota: 50000
    environment:
      - APPNAME={{appname}}
      - REDIS_AUTH_PASSWORD={{PASSWORD}}
      - STARTORDER=7

      - HAPROXY_MAXCONN={{HAPROXY_MAXCONN}}
      - HAPROXY_CONNECT_TIMEOUT={{HAPROXY_CONNECT_TIMEOUT}}
      - HAPROXY_SERVER_TIMEOUT={{HAPROXY_SERVER_TIMEOUT}}
      - HAPROXY_CLIENT_TIMEOUT={{HAPROXY_CLIENT_TIMEOUT}}
      - HAPROXY_BALANCE={{HAPROXY_BALANCE}}
  master:
    image: wind634/redis:ha
    command: --appendonly yes --masterauth {{PASSWORD}}
    labels:
      - "io.daocloud.dce.service.role=master"
      - "io.daocloud.dce.compose.endpoint-spec.mode=dnsrr"
      - io.daocloud.dce.compose.placement.constraints=["node.labels.servicepool1 == servicepool1", "node.labels.redis == redis"]
    volumes:
      - /data
#    cpu_quota: 80000
    environment:
      - STARTORDER=0

      - REDIS_TIMEOUT={{REDIS_TIMEOUT}}
      - REDIS_MAXMEMORY={{REDIS_MAXMEMORY}}
      - REDIS_RDB_COMPRESSION={{REDIS_RDB_COMPRESSION}}
      - REDIS_APPEND_ONLY={{REDIS_APPEND_ONLY}}
      - REDIS_APPEND_FSYNC={{REDIS_APPEND_FSYNC}}
      - REDIS_MAXMEMORY_POLICY={{REDIS_MAXMEMORY_POLICY}}
      - REDIS_PASSWORD={{PASSWORD}}
  slave:
    image: wind634/redis:ha
    labels:
      - "io.daocloud.dce.service.role=slave"
      - "io.daocloud.dce.compose.endpoint-spec.mode=dnsrr"
      - io.daocloud.dce.compose.placement.constraints=["node.labels.servicepool2 == servicepool2", "node.labels.redis == redis"]
    volumes:
      - /data
    command:  --slaveof {{appname}}_master 6379 --appendonly yes --masterauth {{PASSWORD}}
#    restart: unless-stopped
#    cpu_quota: 50000
    environment:
      - STARTORDER=1

      - REDIS_TIMEOUT={{REDIS_TIMEOUT}}
      - REDIS_MAXMEMORY={{REDIS_MAXMEMORY}}
      - REDIS_RDB_COMPRESSION={{REDIS_RDB_COMPRESSION}}
      - REDIS_APPEND_ONLY={{REDIS_APPEND_ONLY}}
      - REDIS_APPEND_FSYNC={{REDIS_APPEND_FSYNC}}
      - REDIS_MAXMEMORY_POLICY={{REDIS_MAXMEMORY_POLICY}}
      - REDIS_PASSWORD={{PASSWORD}}
    depends_on:
      - master
  slave1:
    image: wind634/redis:ha
    labels:
      - "io.daocloud.dce.service.role=slave"
      - "io.daocloud.dce.compose.endpoint-spec.mode=dnsrr"
      - io.daocloud.dce.compose.placement.constraints=["node.labels.servicepool3 == servicepool3", "node.labels.redis == redis"]
    volumes:
      - /data
    command: --slaveof {{appname}}_master 6379 --appendonly yes --masterauth {{PASSWORD}}
#    restart: unless-stopped
#    cpu_quota: 50000
    environment:
      - STARTORDER=2

      - REDIS_TIMEOUT={{REDIS_TIMEOUT}}
      - REDIS_MAXMEMORY={{REDIS_MAXMEMORY}}
      - REDIS_RDB_COMPRESSION={{REDIS_RDB_COMPRESSION}}
      - REDIS_APPEND_ONLY={{REDIS_APPEND_ONLY}}
      - REDIS_APPEND_FSYNC={{REDIS_APPEND_FSYNC}}
      - REDIS_MAXMEMORY_POLICY={{REDIS_MAXMEMORY_POLICY}}
      - REDIS_PASSWORD={{PASSWORD}}
    depends_on:
      - master
  sentinel0:
    image: wind634/redis-sentinel:ha
    labels:
      - io.daocloud.dce.compose.placement.constraints=["node.labels.servicepool1 == servicepool1", "node.labels.redis == redis"]
    ports:
      - "26379"
    environment:
      - APPNAME={{appname}}
      - STARTORDER=3

      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS={{REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS}}
      - REDIS_SENTINEL_PASSWORD={{PASSWORD}}
      - REDIS_SENTINEL_MASTER_HOST={{appname}}_master
      - REDIS_SENTINEL_PARALLEL_SYNCS={{REDIS_SENTINEL_PARALLEL_SYNCS}}
      - REDIS_SENTINEL_FAILOVER_TIMEOUT={{REDIS_SENTINEL_FAILOVER_TIMEOUT}}

    depends_on:
      - master
      - slave
      - slave1
#    cpu_quota: 50000
  sentinel1:
    image: wind634/redis-sentinel:ha
    labels:
      - io.daocloud.dce.compose.placement.constraints=["node.labels.servicepool2 == servicepool2", "node.labels.redis == redis"]
    ports:
      - "26379"
    environment:
      - APPNAME={{appname}}
      - STARTORDER=4

      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS={{REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS}}
      - REDIS_SENTINEL_PASSWORD={{PASSWORD}}
      - REDIS_SENTINEL_MASTER_HOST={{appname}}_master
      - REDIS_SENTINEL_PARALLEL_SYNCS={{REDIS_SENTINEL_PARALLEL_SYNCS}}
      - REDIS_SENTINEL_FAILOVER_TIMEOUT={{REDIS_SENTINEL_FAILOVER_TIMEOUT}}
    depends_on:
      - master
      - slave
      - slave1
#    cpu_quota: 50000
  sentinel2:
    image: wind634/redis-sentinel:ha
    labels:
      - io.daocloud.dce.compose.placement.constraints=["node.labels.servicepool3 == servicepool3", "node.labels.redis == redis"]
    ports:
      - "26379"
    environment:
      - APPNAME={{appname}}
      - STARTORDER=5

      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS={{REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS}}
      - REDIS_SENTINEL_PASSWORD={{PASSWORD}}
      - REDIS_SENTINEL_MASTER_HOST={{appname}}_master
      - REDIS_SENTINEL_PARALLEL_SYNCS={{REDIS_SENTINEL_PARALLEL_SYNCS}}
      - REDIS_SENTINEL_FAILOVER_TIMEOUT={{REDIS_SENTINEL_FAILOVER_TIMEOUT}}
    depends_on:
      - master
      - slave
      - slave1
#    restart: unless-stopped
#    cpu_quota: 50000
#  exporter:
#    image: daocloud.io/daocloud/servicebroker-exporter
#    labels:
#      - "io.daocloud.dce.service.role=exporter"
#    environment:
#      - STARTORDER=6
#      - APPTYPE=redis-ha
#      - APPNAME={{appname}}
#      - HOSTS=redis:master:master:6379,redis:slave:slave:6379,sentinel:sentinel:sentinel:26379,haproxy:haproxy:haproxy:6379 # host=type:role:host:port
#      - USERNAME=redis_has_no_user
#      - PASSWORD={{PASSWORD}}
#    ports:
#      - '9120'