version: '3'
services:
    zoo1:
        image: wind634/zookeeper:3.4.10
#        restart: always
        ports:
            - "2181"
            - "2888"
            - "3888"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888,server.2=zoo2:2888:3888,server.3=zoo3:2888:3888
            # zookeeper一般配置
            ZOO_TICK_TIME: 2000
            ZOO_INIT_LIMIT: 5
            ZOO_SYNC_LIMIT: 2
            # zookeeper的jvm的配置
            ZOO_JVM_XMS: 102400
            ZOO_JVM_XMX: 102400
            ZOO_JVM_XSS: 512
    zoo2:
        image: wind634/zookeeper:3.4.10
#        restart: always
        ports:
            - "2181"
            - "2888"
            - "3888"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888,server.2=zoo2:2888:3888,server.3=zoo3:2888:3888
             # zookeeper一般配置
            ZOO_TICK_TIME: 2000
            ZOO_INIT_LIMIT: 5
            ZOO_SYNC_LIMIT: 2
            # zookeeper的jvm的配置
            ZOO_JVM_XMS: 102400
            ZOO_JVM_XMX: 102400
            ZOO_JVM_XSS: 512
    zoo3:
        image: wind634/zookeeper:3.4.10
#        restart: always
        ports:
            - "2181"
            - "2888"
            - "3888"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888,server.2=zoo2:2888:3888,server.3=zoo3:2888:3888
            # zookeeper一般配置
            ZOO_TICK_TIME: 2000
            ZOO_INIT_LIMIT: 5
            ZOO_SYNC_LIMIT: 2
            # zookeeper的jvm的配置
            ZOO_JVM_XMS: 102400
            ZOO_JVM_XMX: 102400
            ZOO_JVM_XSS: 512
